### ISSUE TITLE
When using Custom HTML tag it should not care about children supplied to  ClipboardButton

### ISSUE THREAD

**Issue by azizur** [nihey/react-clipboard.js#70]
When using Custom HTML tag it should not care about children supplied to  `ClipboardButton`.

I am trying to create a `Clipboard` component like this:
```
<Clipboard component="a" button-href="#" data-clipboard-text={window.location.href}><i className="fa fas fa-link"></i> Copy Link </Clipboard>
```
I am getting this error:
```
Warning: Failed prop type: Invalid prop `children` supplied to `ClipboardButton`.
```

**Comment by nihey** [comment]
@azizur Thanks for reporting, this may be caused by this PR, that is not yet deployed: https://github.com/nihey/react-clipboard.js/pull/67

I'll deploy it now, after that, could you try out to see if this still happens?

**Comment by nihey** [comment]
Done, `2.0.7` is out, could you try out and see if this issue continues?

**Comment by foysalit** [comment]
Hey @nihey I'm using 2.0.7 and still seeing this issue. here's how my code looks:
```
            <Clipboard
                component="span" 
                data-clipboard-text={product.product_id}
            >
                copy text
            </Clipboard>
```

And I'm getting this warning in the console: 
```
Warning: Failed prop type: Invalid prop `children` supplied to `ClipboardButton`.
``` 
any chance of fixing this? let me know if I can help.

**Comment by nihey** [comment]
@foysalit Thanks for reporting, I'll investigate this issue by this week and should give a proper answer for it.

**Comment by uyouthe** [comment]
Me too.

**Comment by nihey** [comment]
@uyouthe Your change should have fixed it on `2.0.8`, could you confirm it? If it does not fix it, you can re-open this issue so we can investigate it a little further.

**Comment by uyouthe** [comment]
@nihey #74

**Comment by Radvile** [comment]
Hi, I'm having the same issue and just updated the version to the most recent. My code example and the error I get is exactly the same as the creators - not sure if there's an update here? Thanks!
